script: fix other startup script. This fixes #4077.

diff --git a/script/other/cbd.init.d.in b/script/other/cbd.init.d.in
--- a/script/other/cbd.init.d.in
+++ b/script/other/cbd.init.d.in
@@ -1,6 +1,6 @@
 #!/bin/sh
 ##
-## Copyright 2009-2012 Merethis
+## Copyright 2009-2013 Merethis
 ##
 ## This file is part of Centreon Broker.
 ##
@@ -38,101 +38,119 @@
 # pidfile: TO_CHANGE
 ### END INIT INFO
 
-# Select distribution type.
-if [ -f "/lib/lsb/init-functions" ] ; then
-  distribution="lsb"
-  . "/lib/lsb/init-functions"
-elif [ -f "/etc/rc.d/init.d/functions" ] ; then
-  distribution="redhat"
-  . "/etc/rc.d/init.d/functions"
-else
-  echo "Unknown distribution type."
-  exit 1
-fi
-
-# Logging functions.
-broker_log_failure() {
-  if [ "$distribution" = "redhat" ] ; then
-    failure $@
-  else
-    log_failure_msg $@
-  fi
-}
-broker_log_success() {
-  if [ "$distribution" = "redhat" ] ; then
-    success $@
-  else
-    log_success_msg $@
-  fi
-}
-
 # Configuration parameters.
-CONFIG_FILE="@PREFIX_CONF@/@DAEMON_NAME@.xml"
-DAEMON_NAME="cbd-@DAEMON_NAME@"
-CBD="@PREFIX_BIN@/cbd"
-PID_PATH=/var/run
-STOP_TIMEOUT=10
+master_file="@PREFIX_CONF@/master.run"
+config_dir="@PREFIX_CONF@"
+cbd="@PREFIX_BIN@/cbd"
+pid_path=/var/run
+stop_timeout=10
 user="@USER@"
 
-# Daemon name must be set.
-if [ -z "${DAEMON_NAME}" ] ; then
-  echo "The cbd name isn't set."
-  exit 1
-fi
-
 # Check that cbd is executable.
-if [ ! -x "${CBD}" ] ; then
+if [ ! -x "${cbd}" ] ; then
   echo "The cbd binary can't be run."
   exit 1
 fi
 
 # Check that configuration file exists.
-if [ ! -e "${CONFIG_FILE}" ] ; then
-  echo "The configuration file isn't found."
+if [ ! -e "${master_file}" ] ; then
+  echo "The master file isn't found."
   exit 1
 fi
 
-# PID file.
-pidfile="${PID_PATH}/${DAEMON_NAME}.pid"
-
 # Start cbd.
 start() {
-  # Check for running.
-  if [ -f "${pidfile}" ] ; then
-    is_running=$(ps -edf | grep "${CBD} ${CONFIG_FILE}" | grep -v grep | wc -l )
-    if [ $is_running = 0 ] ; then
-      rm -f "$pidfile"
-    else
-      echo -n "${DAEMON_NAME} already running"
-      broker_log_failure "cbd startup"
-      return 1
-    fi
-  fi
+  global_retval=0
+  cat ${master_file} | grep -v '^#'| while read line; do
+    daemon_name="cbd_$(echo ${line} | awk '{ print $1 }')"
+    daemon_config="${config_dir}/$(echo ${line} | awk '{ print $2 }')"
+    running="$(echo ${line} | awk '{ print $3 }')"
+    pidfile="${pid_path}/${daemon_name}.pid"
+    if [ "${running}" = "y" ]; then
+      if [ -f "${pidfile}" ] ; then
+        is_running=$(ps -edf | grep "${cbd} ${daemon_config}" | grep -v grep | wc -l )
+        if [ $is_running = 0 ] ; then
+          rm -f "$pidfile"
+        else
+          echo -n "${daemon_name} already running"
+          return 1
+        fi
+      fi
 
-  # Start cbd.
-  echo -n "Starting ${DAEMON_NAME}: "
-  PID=`su - "${user}" -c "${CBD} ${CONFIG_FILE} >/dev/null 2>&1 & echo \\$!"`
-  RETVAL=$?
-  if [ ${RETVAL} = 0 ]; then
-    echo ${PID} > "${pidfile}"
-    broker_log_success "cbd startup"
-  else
-    broker_log_failure "cbd startup"
-  fi
-  return ${RETVAL}
+      # Start cbd.
+      echo -n "Starting ${daemon_name}: "
+      PID=`su - "${user}" -c "${cbd} ${daemon_config} >/dev/null 2>&1 & echo \\$!"`
+      RETVAL=$?
+      if [ ${RETVAL} = 0 ]; then
+        echo ${PID} > "${pidfile}"
+        echo "cbd startup [success]"
+      else
+        ${global_retval} = ${RETVAL}
+        echo "cbd startup [failed]"
+      fi
+      echo
+    fi
+  done
+  return ${global_retval}
 }
 
 # Stop cbd.
 stop() {
-  echo -n "Stopping ${DAEMON_NAME}: "
-  killproc -p "${pidfile}" -d ${STOP_TIMEOUT} "$CBD"
-  RETVAL=$?
-  if [ ${RETVAL} = 0 ] ; then
-    rm -f "${pidfile}"
-    broker_log_success "cbd shutdown"
-  else
-    broker_log_failure "cbd shutdown"
-  fi
+  cat ${master_file} | grep -v '^#'| while read line; do
+    daemon_name="cbd_$(echo ${line} | awk '{ print $1 }')"
+    daemon_config="${config_dir}/$(echo ${line} | awk '{ print $2 }')"
+    running="$(echo ${line} | awk '{ print $3 }')"
+    pidfile="${pid_path}/${daemon_name}.pid"
+    if [ "${running}" = "y" ]; then
+      echo -n "Stopping ${daemon_name}: "
+      kill -TERM `cat "${pidfile}"`
+      sleep ${stop_timeout}
+      kill -KILL `cat "${pidfile}"`
+      RETVAL=$(ps -edf | grep "${cbd} ${daemon_config}" | grep -v grep | wc -l)
+      if [ ${RETVAL} = 0 ] ; then
+        rm -f "${pidfile}"
+        echo "cbd shutdown [success]"
+      else
+        echo "cbd shutdown [failure]"
+      fi
+      echo
+    fi
+  done
+}
+
+# Send kill HUP
+reload() {
+  cat ${master_file} | grep -v '^#'| while read line; do
+    daemon_name="cbd_$(echo ${line} | awk '{ print $1 }')"
+    daemon_config="${config_dir}/$(echo ${line} | awk '{ print $2 }')"
+    running="$(echo ${line} | awk '{ print $3 }')"
+    reload="$(echo ${line} | awk '{ print $4 }')"
+    pidfile="${pid_path}/${daemon_name}.pid"
+    if [ "${running}" = "y" -a "${reload}" = "y" ]; then
+      echo -n "Reloading ${daemon_name}: "
+      kill -HUP `cat "${pidfile}"`
+      RETVAL=$?
+      if [ ${RETVAL} = 0 ]; then
+        echo "cbd reload [success]"
+      else
+        echo "cbd reload [failure]"
+      fi
+      echo
+    fi
+  done
+}
+
+# Status
+status_all() {
+  cat ${master_file} | grep -v '^#'| while read line; do
+    daemon_name="cbd_$(echo ${line} | awk '{ print $1 }')"
+    daemon_config="${config_dir}/$(echo ${line} | awk '{ print $2 }')"
+    running="$(echo ${line} | awk '{ print $3 }')"
+    pidfile="${pid_path}/${daemon_name}.pid"
+    if [ "${running}" = "y" ]; then
+      status -p ${pidfile} ${cbd}
+    fi
+  done
 }
 
 # Switch case.
@@ -147,12 +165,15 @@ case "$1" in
     stop
     start
     ;;
+  reload)
+    reload
+    ;;
   status)
-    status -p ${pidfile} ${cbd}
+    status_all
     RETVAL=$?
     ;;
   *)
-    echo "Usage: ${DAEMON_NAME} {start|stop|restart|status}"
+    echo "Usage: ${daemon_name} {start|stop|restart|status}"
     exit 1
 esac
 
