Implemented the 'status' feature for the SysV-style startup script.
git-svn-id: http://svn.modules.centreon.com/centreon-broker/trunk@1364 7c7d615a-03b3-410d-a316-1135b1bd9499

diff --git a/script/sysv_init_script.sh.in b/script/sysv_init_script.sh.in
--- a/script/sysv_init_script.sh.in
+++ b/script/sysv_init_script.sh.in
@@ -137,6 +137,23 @@ stop() {
   else
     broker_log_failure "cbd shutdown"
   fi
+  return ${RETVAL}
+}
+
+# Get cbd status.
+status() {
+  if [ ! -f "${pidfile}" ] ; then
+    RETVAL=3
+  else
+    pid=`head -n 1 "${pidfile}"`
+    kill -0 "${pid}"
+    RETVAL=$?
+    # LSB-compliant return code.
+    if [ ${RETVAL} -ne 0 ] ; then
+      RETVAL=1
+    fi
+  fi
+  return ${RETVAL}
 }
 
 # Switch case.
@@ -152,7 +169,7 @@ case "$1" in
     start
     ;;
   status)
-    status -p ${pidfile} ${cbd}
+    status
     RETVAL=$?
     ;;
   *)
